# config/application.yml
defaults: &defaults
  Cimiss:
    min_rain_time_range: 
      title: 分钟雨量累加 按时间段地区查询
      url: "http://t.weather-huayun.com:8080/cimiss-web/api?userId=BCSH_SHSJ_api&pwd=67739161&interfaceId=statSurfEleInRegion&dataCode=SURF_CHN_PRE_MIN&elements=Station_Name&statEles=Sum_PRE&timeRange=[#{time1},#{time2}]&adminCodes=310117&dataFormat=json"
    oclock_rain_time_range: 
      title: 整点小时雨量累加 按时间段地区查询 
      url: "http://t.weather-huayun.com:8080/cimiss-web/api?userId=BCSH_SHSJ_api&pwd=67739161&interfaceId=statSurfPreInRegion&elements=Station_Name,Station_Id_C&timeRange=[#{time1},#{time2}]&adminCodes=310117&limitCnt=30&dataFormat=html"
  LocationUtil:
    ak: '200aadcf1ccf720749c79228f9b7fd79'
    remote: 'http://api.map.baidu.com'
    api_path: 'geocoder/v2/'
  Weather::WeatherForecasts:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/weather_forecasts/query'
    remote: 'http://61.152.122.112:8080/'
  Weather::RealTimeStation:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/auto_stations/locate_site'
    remote: 'http://61.152.122.112:8080/'
  Aqi::RealTimeAqi:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/aqi'
    remote: 'http://61.152.122.112:8080/'
  Aqi::ForecastAirQuality:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/aqi/forecast'
    remote: 'http://61.152.122.112:8080/'
  Aqi::AqiHistory:
    api_path: 'aqi_avg_hours/'
    remote: 'http://222.66.83.20:9090/'
  Warning::CityWarning:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/warnings/city'
    remote: 'http://61.152.122.112:8080/'
  Warning::SongjiangWarning:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/warnings/district'
    remote: 'http://61.152.122.112:8080/'
  AutoStation::Statistic:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/auto_stations/statistic'
    remote: 'http://61.152.122.112:8080/'
  AutoStation::History:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/auto_stations/history'
    remote: 'http://61.152.122.112:8080/'
  Typhoon::TyphoonList:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/typhoons'
    remote: 'http://61.152.122.112:8080/'
  Typhoon::TyphoonDetail:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/typhoons/'
    remote: 'http://61.152.122.112:8080/'
  Radar::RadarEcho:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/city_weathers/radars/up_to'
    remote: 'http://61.152.122.112:8080/'
  Image::CloudData:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/images'
    remote: 'http://61.152.122.112:8080/'
  Image::CloudFy2gData:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/images'
    remote: 'http://61.152.122.112:8080/'
  Radar::RadarImageProcess:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/images'
    remote: 'http://61.152.122.112:8080/'
  QpRadarImageProcess:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/images'
    remote: 'http://61.152.122.112:8080/'
  Image::DemData:
    appid: 'bFLKk0uV7IZvzcBoWJ1j'
    appkey: 'mXwnhDkYIG6S9iOyqsAW7vPVQ5ZxBe'
    api_path: '/api/v1/images/dem'
    remote: 'http://61.152.122.112:8080/'
development:
  <<: *defaults

test:
  <<: *defaults

production:
  <<: *defaults
